---
version: 1
environments:
  - name: common
    vars:
      EXAMPLE_COMMON: some-common-value
      EXAMPLE_USER: env://USER
      EXAMPLE_SECRET1: secret+google:///projects/default-project-235223/secrets/example-secret#AAA
      EXAMPLE_SECRET2: secret+google:///projects/default-project-235223/secrets/unknown-secret?default=foo#BBB

  - name: local
    extends:
      - common
    vars:
      EXAMPLE_VALUE: some-local-value
      AAA: "something"
      BBB: "something with spaces"
      CCC: 'something "quoted"'
      DDD: |
        something
        multiline

  - name: staging
    extends:
      - common
    vars:
      EXAMPLE_VALUE: some-staging-value
