version: "2"

linters:
  default: all
  disable:
    - containedctx
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gocognit
    - godox
    - gochecknoglobals
    - gochecknoinits
    - mnd
    - nlreturn
    - noinlineerr
    - paralleltest
    - revive
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5

  exclusions:
    rules:
      - path: _test.go
        linters:
          - goconst
      - source: "^\\s*defer\\s+"
        linters:
          - errcheck
          - staticcheck

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    lll:
      line-length: 120

severity:
  default: error
