project_name: envctl

before:
  hooks:
    - go mod tidy
    - ./bin/completions.sh
    - ./bin/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    # `flags`, `ldflags`, and `mod_timestamp` are configured for reproducible builds.
    # See: https://goreleaser.com/customization/builds/#reproducible-builds
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - src: build/completions/*
        dst: completions
        strip_parent: true
      - src: build/manpages/*
        dst: manpages
        strip_parent: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    rlcp: true

brews:
  - tap:
      owner: twelvelabs
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/twelvelabs/envctl"
    description: "Manage project environment variables"
    license: "MIT"
    install: |-
      bin.install "envctl"
      bash_completion.install "completions/envctl.bash" => "envctl"
      zsh_completion.install "completions/envctl.zsh" => "_envctl"
      fish_completion.install "completions/envctl.fish"
      man1.install "manpages/envctl.1.gz"
    test: |
      system "#{bin}/envctl --version"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next" # cspell: disable-line

changelog:
  use: github
  sort: asc
  groups:
    - title: New features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 99
