version: 1
environments:
  - name: common
    vars:
      EXAMPLE_COMMON: some-common-value
      # EXAMPLE_USER: env://USER
      # EXAMPLE_SECRET: secret+google:///projects/my-project-id/secrets/my-secret-id#EXAMPLE_SECRET

  - name: local
    extends:
      - common
    vars:
      EXAMPLE: hello local

  - name: staging
    extends:
      - common
    vars:
      EXAMPLE: hello staging

  - name: prod
    extends:
      - common
    vars:
      EXAMPLE: hello prod
