---
name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read
  packages: write # push docker images
  id-token: write # keyless gitsign

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2
        with:
          fetch-depth: 0
          # Need a PAT so that `make release-tag` will trigger the release workflow.
          # See: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          token: ${{ secrets.GH_PAT }}

      - name: Set up Homebrew
        uses: homebrew/actions/setup-homebrew@a1377360f443cba4201fe7a591d1c60ba7ddab7a # pin@master

      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # pin@v4.0.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: make setup

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        run: make lint

      - name: Coverage
        uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # pin@v3.1.3

      - name: Create release tag
        # Change to support different release channels
        # Versions from a non-main branch will look like: `v.0.0.0-branch-name`.
        if: contains(fromJSON('["main", "beta"]'), github.ref_name)
        run: make release-tag
